app:
  testing:
    base-url: ENC(+P0MZlwAJrJ6UWqN8Vqq1WfRRWgV4RfPrJE3VLmUmFk=)
  datasource-testing:
    jdbc-url: ENC(e+9jJZudYm8cHwrXNF9AKuo6GbWWgViSl3+tIYr5O0zRJ1qRIcuOsGqniY270AaG)
    username: ENC(1Kq0vluoQ1Vp3Fn9C5FCntojLhDnTtxd)
    password: ENC(3XI6tcCl9ss7+DZ9SeMExg==)
    pool-size: 3
  datasource-production:
    jdbc-url: ENC(ouQk/6lxDXEKWg48w4UDUEKjuH9eIZpc3Nb7w0wFnyPzgdIZW0q38VgUaLhSSgg6)
    username: ENC(1Kq0vluoQ1Vp3Fn9C5FCntojLhDnTtxd)
    password: ENC(3XI6tcCl9ss7+DZ9SeMExg==)
    pool-size: 3